# Generated by Django 4.1.7 on 2023-03-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_booksearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='launch_books',
            field=models.BooleanField(default=False),
        ),
    ]
